// packages/react/esm/SkeletonBlock.js
function _extends() {
  _extends =
    Object.assign ||
    function (target) {
      for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i];
        for (var key in source) {
          if (Object.prototype.hasOwnProperty.call(source, key)) {
            target[key] = source[key];
          }
        }
      }
      return target;
    };
  return _extends.apply(this, arguments);
}

function _objectWithoutPropertiesLoose(source, excluded) {
  if (source == null) return {};
  var target = {};
  var sourceKeys = Object.keys(source);
  var key, i;
  for (i = 0; i < sourceKeys.length; i++) {
    key = sourceKeys[i];
    if (excluded.indexOf(key) >= 0) continue;
    target[key] = source[key];
  }
  return target;
}

import React from 'react';

var SkeletonBlock = function SkeletonBlock(_temp) {
  var _ref = _temp === void 0 ? {} : _temp,
    _ref$tag = _ref.tag,
    Tag = _ref$tag === void 0 ? 'div' : _ref$tag,
    width = _ref.width,
    height = _ref.height,
    effect = _ref.effect,
    className = _ref.className,
    style = _ref.style,
    children = _ref.children,
    other = _objectWithoutPropertiesLoose(_ref, [
      'tag',
      'width',
      'height',
      'effect',
      'className',
      'style',
      'children',
    ]);

  var skeletonStyle = style || {};
  if (width) skeletonStyle.width = width;
  if (height) skeletonStyle.height = height;
  var skeletonClassName = [
    'skeleton-block',
    effect && 'skeleton-effect-' + effect,
    className,
  ]
    .filter(function (c) {
      return !!c;
    })
    .join(' ');
  return /*#__PURE__*/ React.createElement(
    Tag,
    _extends(
      {
        style: skeletonStyle,
        className: skeletonClassName,
      },
      other,
    ),
    children,
  );
};

export default SkeletonBlock;

// src/svelte/SkeletonBlock.svelte
{#if tag === 'div'}
  <div {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></div>
{:else if tag === 'p'}
  <p {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></p>
{:else if tag === 'h1'}
  <h1 {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></h1>
{:else if tag === 'h2'}
  <h2 {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></h2>
{:else if tag === 'h3'}
  <h3 {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></h3>
{:else if tag === 'h4'}
  <h4 {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></h4>
{:else if tag === 'h5'}
  <h5 {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></h5>
{:else}
  <span {...rest} style={skeletonStyle} class={skeletonClassName}><slot /></span>
{/if}
<script>
  export let width = undefined;
  export let height = undefined;

  export let tag = 'div';
  export let effect = undefined;

  export let style = undefined;
  let className = undefined;
  export { className as class };

  let rest = {};
  $: Object.keys($$props).forEach((prop) => {
    if (
      prop !== 'width'
      && prop !== 'height'
      && prop !== 'tag'
      && prop !== 'effect'
      && prop !== 'style'
      && prop !== 'class'
    ) {
      rest[prop] = $$props[prop];
    }
  });

  $: skeletonStyle = style || '';
  $: if (width) skeletonStyle += `;width: ${width}`;
  $: if (height) skeletonStyle += `;height: ${height}`;

  $: skeletonClassName = [
    'skeleton-block',
    effect && `skeleton-effect-${effect}`,
    className
  ]
    .filter(c => !!c)
    .join(' ');

</script>
