// src/react/skeleton-text.js
import React from 'react';

const SkeletonText = ({
  tag: Tag = 'span',
  effect,
  className,
  children,
  ...other
} = {}) => {
  const skeletonClassName = [
    'skeleton-text',
    effect && `skeleton-effect-${effect}`,
    className
  ]
    .filter(c => !!c)
    .join(' ');

  return (
    <Tag className={skeletonClassName} {...other}>{children}</Tag>
  )
};

export default SkeletonText;

// src/vue/skeleton-text.vue
<script>
  export default {
    name: 'skeleton-text',
    props: {
      tag: {
        type: String,
        default: 'span',
      },
      effect: String,
    },
    render() {
      const h = this.$createElement;
      return h(
        this.tag,
        {
          class: {
            'skeleton-text': true,
            [`skeleton-effect-${this.effect}`]: this.effect,
          }
        },
        [
          this.$slots.default,
        ],
      );
    }
  }
</script>
